name: beersp_demo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  google_fonts: ^6.1.0
  flutter:
    sdk: flutter

  # Iconos estilo iOS
  cupertino_icons: ^1.0.8

  #para las imágenes de las cervezas jejej
  image_picker: ^1.1.1

  # Firebase núcleo (obligatorio siempre)
  firebase_core: ^4.1.1

  # Firebase Authentication (registro/login)
  firebase_auth: ^6.1.0

  # Cloud Firestore (perfiles, degustaciones, amigos, galardones…)
  cloud_firestore: ^6.0.2

  # Firebase Storage (subir fotos de perfil, cervezas, etc.)
  firebase_storage: ^13.0.2

  # Navegación declarativa
  go_router: ^17.0.0

  # Gestión de estado sencilla
  provider: ^6.0.0

  # Fechas/números internacionales
  intl: ^0.20.2

  # Cargar imágenes con caché
  cached_network_image: ^3.3.0

  async: ^2.10.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

assets:
  - assets/default_avatar.png